Repository gurkult/gurkbot, pull requests merged in 2021-01, with the labels that each got.

#45 Send message to devlog channel on startup
  .env-example
  bot/bot.py
  bot/constants.py
Labels: area: utilities, status: WIP, type: feature

#62 merge develop into main
  .env-example
  bot/bot.py
  bot/constants.py
  bot/exts/utils/_eval_helper.py
  bot/exts/utils/eval.py
Labels: area: meta, type: enhancement

#64 Optimize linting workflow
  .github/workflows/linting.yml
  Pipfile.lock
Labels: area: CI/CD, type: enhancement

#63 Add Docker setup
  .github/workflows/push_container.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  docker-compose.yaml
Labels: area: CI/CD, type: feature

#33 Isgurkan command And gurkancount command
  .github/workflows/linting.yml
  Pipfile
  Pipfile.lock
  bot/bot.py
  bot/constants.py
  bot/exts/gurkan/gurkan_stats.py
  bot/utils/is_gurkan.py
Labels: area: commands, area: utilities, status: WIP, type: feature

#34 Feature/error handler
  .env-example
  .github/workflows/linting.yml
  .github/workflows/push_container.yml
  Pipfile.lock
  bot/constants.py
  bot/exts/backend/__init__.py
  bot/exts/backend/error_handler.py
  bot/exts/utils/eval.py
  bot/resources/bot_replies.yml
  bot/utils/checks.py
  docker-compose.yaml
Labels: area: backend, priority: high, status: WIP, type: feature

#47 Updated README
  README.md
Labels: area: documentation, status: WIP, type: enhancement

#66 Add Gitub Category
  .env-example
  bot/bot.py
  bot/constants.py
  bot/exts/github/__init__.py
  bot/exts/github/_issues.py
  bot/exts/github/_profile.py
  bot/exts/github/_source.py
  bot/exts/github/github.py
  docker-compose.yaml
Labels: area: commands, type: feature

#81 Updated wrong ids in constants.py
  bot/constants.py
Labels: area: commands, priority: high, type: bug
