Repository gurkult/gurkbot, pull requests merged in 2022-01, with the labels that each got.

#169 FEAT: Use isort instead of flake-import-order
  .pre-commit-config.yaml
  bot/__main__.py
  bot/bot.py
  bot/exts/backend/error_handler.py
  bot/exts/fun/bonker.py
  bot/exts/fun/ciphers.py
  bot/exts/fun/off_topic.py
  bot/exts/fun/xkcd.py
  bot/exts/github/_issues.py
  bot/exts/github/_profile.py
  bot/exts/github/_source.py
  bot/exts/github/github.py
  bot/exts/gurkan/gurkan_stats.py
  bot/exts/gurkan/gurkify.py
  bot/exts/gurkan/make_gurkan.py
  bot/exts/gurkcraft/gurkcraft.py
  bot/exts/moderation/logs.py
  bot/exts/moderation/mod_utils.py
  bot/exts/utils/bot_stats.py
  bot/exts/utils/color.py
  bot/exts/utils/eval.py
  bot/exts/utils/reminder.py
  bot/exts/utils/subscription.py
  bot/exts/utils/utils.py
  bot/utils/pagination.py
  bot/utils/parsers.py
  poetry.lock
  poetry.toml
  pyproject.toml
Labels: type: enhancement, area: CI/CD, status: WIP

#173 Add #gurkcraft-relay support
  bot/constants.py
  bot/exts/gurkcraft/gurkcraft.py
  docker-compose.yaml
Labels: type: enhancement, area: UI/UX, status: needs review

#167 feat: add test guild configuration for application commands
  .env-example
  bot/bot.py
  bot/constants.py
Labels: type: bug, area: backend, priority: high, status: needs review
